version: '2'
# Define services
services:
  # External tools
  estimator-redis:
    image: redis
    ports:
      - "6381:6379"
    network_mode: "host"
  estimator-activemq:
    image: webcenter/activemq
    ports:
      - "61618:61616"
    network_mode: "host"
  estimator-mysql:
    image: mysql
    ports:
      - "3308:3306"
    environment:
      - MYSQL_USER=estimator
      - MYSQL_PASSWORD=estimator
      - MYSQL_DATABASE=estimator
      - MYSQL_ROOT_PASSWORD=root
    network_mode: "host"