server:
    port: 19002
    session:
        timeout: 900
spring:
    profiles:
        active: dev
vaadin:
    servlet:
        productionMode: true
eureka:
    client:
        # This is a client, it should not register itself
        register-with-eureka: false
        serviceUrl:
            # Location of Eureka server
            defaultZone: http://localhost:8761/eureka/